version: '3.8'

services:
  stats-server:
    build:
      context: ./stats-server
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  ewm-service:
    build:
      context: ./ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
